# Default values for users API.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# K8s namespace
namespace: tfm-dev-amartinm82

# MySQL
mysql:
  create: false
  image:
    repository: mysql
    tag: 8.0.22
  host: localhost
  user: root
  password: password
  database: users
  port: 3306
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# security context
securityContext:
  runAsUser: 1001

replicaCount: 1

image:
  repository: amartinm82/tfm-users
  tag: "latest"

service:
  type: ClusterIP
  port: 3443

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"