{{ if .Values.mysql.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.pvc" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ end }}