{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user.secrets" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  mysqlpass: {{ .Values.mysql.password }}
{{- end }}
